# Generated by Django 4.2.2 on 2023-06-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
