# Generated by Django 4.2.2 on 2023-07-04 04:32

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image-error.jpg', editable=False, help_text='Select image file to upload', max_length=250, null=True, upload_to=application.models.upload_to, verbose_name='Product Image'),
        ),
    ]
