# Generated by Django 4.2.2 on 2023-07-08 07:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
