# Generated by Django 4.2.2 on 2023-07-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
