# Generated by Django 4.2.2 on 2023-07-09 07:59

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime.now()),
        ),
    ]
