# Generated by Django 4.2.2 on 2023-07-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_order_created_remove_order_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submitted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='application.order'),
        ),
    ]
