# Generated by Django 4.2.2 on 2023-07-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_order_processsed_alter_order_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
