# Generated by Django 4.2.2 on 2023-07-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_order_user_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku']},
        ),
    ]
